### PR TITLE
added top category section

### PR DESCRIPTION
**Pull request by 03amir**
added top category section

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Try to adjust images it shouldn't stretch

**Comment by 03amir** [comment]
is it ok now?

**Comment by smaranjitghose** [comment]
top_cat

Everything looks fine! Just the cards are stretched in the mobile version. Perhaps give a follow-up PR for the fix?

**Pull request merged**
