### PR TITLE
Added Basic Navbar

### LINKED ISSUE #17: Add Basic NavBar
# Directions
- [Sample Reference](https://app-promotional-website.vercel.app/)
- Consult with @anushbhatia for the color and the font
- It should have Home, Categories, Contact, Blog, Team
- Make sure it is mobile responsive

### PR DESCRIPTION
**Pull request by Shruti025**
Fixes: #17 
I have added a basic navbar along with hamburger menu for smaller screens

### CODE REVIEW

**Comment by Shruti025** [comment]
@smaranjitghose @anushbhatia kindly review this PR

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Also add the navigation path to them

**Review by anushbhatia — COMMENTED** [review]
image
roboto is current font family check once if its loaded

**Comment by Shruti025** [comment]
Hey @anushbhatia I have added the links to Home, Contact and Team. Also the font issue is fixed too.

**Pull request merged**
