### PR TITLE
Feat/footer team page

### LINKED ISSUE #50: Add Footer to Team Page
*Self Explanatory*

### PR DESCRIPTION
**Pull request by r3yc0n1c**
Fixed issue #50 

---

Animation

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@r3yc0n1c Everything looks fine. Just incorporate the recent fix to contributor images on the team page to resolve the merger conflicts

**Comment by r3yc0n1c** [comment]
> @r3yc0n1c Everything looks fine. Just incorporate the recent fix to contributor images on the team page to resolve the merger conflicts

fixed the conflicts and added some new styles to the Cards... let me know if I need to change anything...

**Comment by anushbhatia** [comment]
```
src/pages/Team/Team.jsx
src/pages/Team/team.css
```
some errors in these

**Comment by r3yc0n1c** [comment]
resolved the merger conflicts and updated everything... let me know if I need to change anything else... thanks in advance

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
