### PR TITLE
Fixed the responsiveness of contact page

### PR DESCRIPTION
**Pull request by Deepak8717**
fixed responsiveness of contact page. will work on validation and animation part on separate PR

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image

**Comment by Deepak8717** [comment]
Hi, Changes have been updated. Kindly Please check.

**Comment by smaranjitghose** [comment]
> image

The issue still persists

**Comment by Deepak8717** [comment]
Hello @anushbhatia , It's working very well on my end. Could check the following url 
https://indokhaadyam-git-fork-deepak8717-main-smaranjitghose.vercel.app/Contact
also attaching the screenshot
Screenshot from 2022-03-05 13-30-41

Please note that i have tested it well zooming in and out as well as on multiple screen size

**Pull request merged**
